### ISSUE TITLE
添加为知笔记，Origin无法输入端口。

### ISSUE THREAD

**Issue by edwinhuish** [webclipper/web-clipper#1029]
**Bug 描述**

添加为知笔记账户的origin一栏无法输入端口号，按冒号无反应。

**复现步骤**

重现的步骤：

1. 打开 '设置'
2. 点击按钮 '添加账户'
3. 选择类型为 '为知笔记'
4. Origin 输入带端口的域名（无法输入冒号），和 #690 一样的问题

**预期行为**

正确输入带端口的域名或者ip

**Comment by wellgone** [comment]
没修复这个问题之前，可以通过先输入端口号再打冒号来解决。

**Comment by hardheadedmooseknuckle** [comment]
This is the above chinese writing translated to english Added as a note, Origin cannot enter the port. #1029
 Open
edwinhuish opened this issue Mar 2, 2022 1 comment
Comments
@edwinhuish
edwinhuish commented Mar 2, 2022 •
Bug description

The port number cannot be entered in the origin column of the account added as a Zhinote account, and there is no response by pressing the colon.

Steps to reproduce

Steps to reproduce:

Open 'Settings'
Click on the button 'Add Account'
Select the type as 'Weizhi Notes'
Origin Enter a domain name with a port (cannot enter a colon), the same problem as the port number #690 that cannot be specified as Zhinote
expected behavior

Enter the domain name or ip with the port correctly

 @wellgone
wellgone commented Mar 7, 2022
Before this problem is fixed, it can be solved by entering the port number first and then typing a colon.
