### ISSUE TITLE
希望支持本地WebDav功能！

### ISSUE THREAD

**Issue by erikaemma** [webclipper/web-clipper#1030]
**Bug 描述**

1. 下载https://github.com/hacdias/webdav的二进制包；
2. 配置yaml，设置端口为80，删除不必要的用户，设置共享位置与modify权限；
3. 启动webadv，设置webcliper的webdav为http://127.0.0.1，添加账号密码；
4. 使用剪藏功能：“保存内容”按钮是灰色的！

**复现步骤**

1. 下载https://github.com/hacdias/webdav的二进制包；
2. 配置yaml，设置端口为80，删除不必要的用户，设置共享位置与modify权限；
3. 启动webadv，设置webcliper的webdav为http://127.0.0.1，添加账号密码；
4. 使用剪藏功能：“保存内容”按钮是灰色的！

**预期行为**

1. 预期应该能够保存下来
2. 应该能够输入任意端口的ip地址，而不是强制使用80端口！

**截图**

如果适用，请添加屏幕截图以帮助解释您的问题。

**请填写以下信息**

- 笔记平台: WebDav
- 浏览器 chrome
- 版本 98.0.4758.102

**其他背景**

在此处添加有关该问题的任何其他上下文。

**Comment by cxshou** [comment]
自定义端口号，希望早日加入

**Comment by hardheadedmooseknuckle** [comment]
This is the above chinese writing translated to english  Hope to support native WebDav functionality! #1030
 Open
erikaemma opened this issue Mar 3, 2022 1 comment
Comments
@erikaemma
erikaemma commented Mar 3, 2022
Bug description

Download the binary package from https://github.com/hacdias/webdav;
Configure yaml, set the port to 80, delete unnecessary users, set the shared location and modify permissions;
Start webadv, set the webdav of webcliper to http://127.0.0.1, and add the account password;
Use the clipping feature: the "Save Content" button is greyed out!
Steps to reproduce

Download the binary package from https://github.com/hacdias/webdav;
Configure yaml, set the port to 80, delete unnecessary users, set the shared location and modify permissions;
Start webadv, set the webdav of webcliper to http://127.0.0.1, and add the account password;
Use the clipping feature: the "Save Content" button is greyed out!
expected behavior

Expectations should be able to save
Should be able to enter the ip address of any port instead of forcing port 80!
screenshot

If applicable, please add screenshots to help explain your problem.

Please fill in the following information

Note Platform: WebDav
browser chrome
Version 98.0.4758.102
other background

Add any additional context about the issue here.
