### ISSUE TITLE
绑定思源笔记账户出错

### ISSUE THREAD

**Issue by Ultramarinefantasy** [webclipper/web-clipper#888]
**Bug 描述**

在绑定思源账户输入token后，点击校验出现请求失败

![image](https://user-images.githubusercontent.com/54146035/128795346-486aa85d-77ba-42c4-ae69-8e5349a441b5.png)

查看浏览器收集的错误时发现以下内容

> Access to fetch at 'http://127.0.0.1:6806/api/notebook/ls' from origin 'chrome-extension://eppeomkelicmmfoebpejgldbkendcodg' has been blocked by CORS policy: Request header field authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**请填写以下信息**

- 笔记平台: 思源笔记
- 浏览器 ：edge
- 版本：94.0.972.2

**Comment by huoshiyinggong** [comment]
一样的问题

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/128891707-bc5e9268-fe6b-4880-8a8e-b2caf75cd9ce.png)


是否使用了 api token ? 思源笔记是什么版本

**Comment by DiamondYuan** [comment]
@huoshiyinggong  @Ultramarinefantasy

**Comment by Ultramarinefantasy** [comment]
> @huoshiyinggong @Ultramarinefantasy

webclipper升到10，思源笔记版本1.2.31，在开鉴权后填token，使用没问题，可以绑定思源笔记账户，并将笔记保存到思源的笔记本中

**Comment by huoshiyinggong** [comment]
是的，可以绑定账户了，只是保存到笔记中无法显示，版本webclipper10，1.2.31









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "webclipper/web-clipper"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月11日(星期三) 上午7:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [webclipper/web-clipper] 绑定思源笔记账户出错 (#888)





  
@huoshiyinggong @Ultramarinefantasy
  
webclipper升到10，思源笔记版本1.2.31，在开鉴权后填token，使用没问题，可以绑定思源笔记账户，并将笔记保存到思源的笔记本中
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by abtxu** [comment]
> > @huoshiyinggong @Ultramarinefantasy
> 
> webclipper升到10，思源笔记版本1.2.31，在开鉴权后填token，使用没问题，可以绑定思源笔记账户，并将笔记保存到思源的笔记本中


请问怎么开鉴权？
下拉菜单中根本就没有思源笔记的选项
